language: generic
sudo: required
services:
        - docker
before_install:
        - docker build -t karanshreds/react-test -f ./client/Dockerfile.dev ./client
script: 
        - docker run -e CI=true karanshreds/react-test npm test 

after_success: 
        - docker build -t karanshreds/multi-client ./client
        - docker build -t karanshreds/multi-worker ./worker
        - docker build -t karanshreds/multi-server ./server
        - docker build -t karanshreds/multi-nginx ./nginx
        - echo "$docker_password" | docker push -u "$docker_username" --password-stdin
        - docker push karanshreds/multi-client 
        - docker push karanshreds/multi-server
        - docker push karanshreds/multi-nginx 
        - docker push karanshreds/multi-worker
deploy:
        edge: true
        provider: elasticbeanstalk
        region: us-east-1
        app: multi-docker
        env: MultiDocker-env
        bucket_name: elasticbeanstalk-us-east-1-412841717530
        bucket_path: docker-multi
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
