language: generic
sudo: required
services:
        - docker
before_install:
        - docker build -t karanshreds/react-test -f ./client/Dockerfile.dev
script: 
        - docker run -e CI=true karanshreds/react-test npm test 
